# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-metrics-sdk` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-metrics-sdk`.


# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics.rb:10
module OpenTelemetry; end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics.rb:11
module OpenTelemetry::SDK; end

class OpenTelemetry::SDK::Configurator
  include ::OpenTelemetry::SDK::Metrics::ConfiguratorPatch
end

# The Instrument module contains the OpenTelemetry instruments reference
# implementation.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument.rb:11
module OpenTelemetry::SDK::Instrument; end

# The Metrics module contains the OpenTelemetry metrics reference
# implementation.
# The Metrics module contains the OpenTelemetry metrics reference
# implementation.
# The Metrics module contains the OpenTelemetry metrics reference
# implementation.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics.rb:14
module OpenTelemetry::SDK::Metrics; end

# The Aggregation module contains the OpenTelemetry metrics reference
# aggregation implementations.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation.rb:12
module OpenTelemetry::SDK::Metrics::Aggregation; end

# AggregationTemporality represents the temporality of
# data point ({NumberDataPoint} and {HistogramDataPoint}) in {Metrics}.
# It determine whether the data point will be cleared for each metrics pull/export.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:14
class OpenTelemetry::SDK::Metrics::Aggregation::AggregationTemporality
  # @api private
  # The constructor is private and only for use internally by the class.
  # Users should use the {delta} and {cumulative} factory methods to obtain
  # a {AggregationTemporality} instance.
  #
  # @param [Integer] temporality One of the status codes below
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:66
  def initialize(temporality); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:74
  def cumulative?; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:70
  def delta?; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:58
  def temporality; end

  class << self
    # Returns a newly created {AggregationTemporality} with temporality == CUMULATIVE
    #
    # @return [AggregationTemporality]
    #
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:28
    def cumulative; end

    # Returns a newly created {AggregationTemporality} with temporality == DELTA
    #
    # @return [AggregationTemporality]
    #
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:21
    def delta; end

    # |------------------|------------|------------------|----------- |---------------|-------------------- |
    #
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:37
    def determine_temporality(aggregation_temporality: T.unsafe(nil), instrument_kind: T.unsafe(nil), default: T.unsafe(nil)); end

    private

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:16
    def new(*_arg0); end
  end
end

# cumulative: data point will NOT be cleared after metrics pull/export.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:82
OpenTelemetry::SDK::Metrics::Aggregation::AggregationTemporality::CUMULATIVE = T.let(T.unsafe(nil), Symbol)

# delta: data point will be cleared after each metrics pull/export.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/aggregation_temporality.rb:79
OpenTelemetry::SDK::Metrics::Aggregation::AggregationTemporality::DELTA = T.let(T.unsafe(nil), Symbol)

# Contains the implementation of the Drop aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/drop.rb:12
class OpenTelemetry::SDK::Metrics::Aggregation::Drop
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/drop.rb:17
  def initialize(exemplar_reservoir: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/drop.rb:21
  def collect(start_time, end_time, data_points); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/drop.rb:25
  def update(increment, attributes, data_points, exemplar_offer: T.unsafe(nil)); end
end

# Use noop reservoir since this is a no-op aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/drop.rb:14
OpenTelemetry::SDK::Metrics::Aggregation::Drop::DEFAULT_RESERVOIR = T.let(T.unsafe(nil), OpenTelemetry::SDK::Metrics::Exemplar::NoopExemplarReservoir)

# Contains the implementation of the ExplicitBucketHistogram aggregation
# https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExplicitBucketHistogram
  # The default value for boundaries represents the following buckets:
  # (-inf, 0], (0, 5.0], (5.0, 10.0], (10.0, 25.0], (25.0, 50.0],
  # (50.0, 75.0], (75.0, 100.0], (100.0, 250.0], (250.0, 500.0],
  # (500.0, 1000.0], (1000.0, +inf)
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:23
  def initialize(aggregation_temporality: T.unsafe(nil), boundaries: T.unsafe(nil), record_min_max: T.unsafe(nil), exemplar_reservoir: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:111
  def aggregation_temporality; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:36
  def collect(start_time, end_time, data_points); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:14
  def exemplar_reservoir; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:62
  def update(amount, attributes, data_points, exemplar_offer: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:117
  def empty_bucket_counts; end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/explicit_bucket_histogram.rb:16
OpenTelemetry::SDK::Metrics::Aggregation::ExplicitBucketHistogram::DEFAULT_BOUNDARIES = T.let(T.unsafe(nil), Array)

# Contains the implementation of the {https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exponentialhistogram ExponentialBucketHistogram} aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:19
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram
  # The default boundaries are calculated based on default max_size and max_scale values
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:35
  def initialize(aggregation_temporality: T.unsafe(nil), max_size: T.unsafe(nil), max_scale: T.unsafe(nil), record_min_max: T.unsafe(nil), zero_threshold: T.unsafe(nil), exemplar_reservoir: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:346
  def aggregation_temporality; end

  # when aggregation temporality is cumulative, merge and downscale will happen.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:76
  def collect(start_time, end_time, data_points); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:28
  def exemplar_reservoir; end

  # this is aggregate in python; there is no merge in aggregate; but rescale happened
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:225
  def update(amount, attributes, data_points, exemplar_offer: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:378
  def downscale(change, positive, negative); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:364
  def empty_counts; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:414
  def get_low_high(buckets, scale, min_scale); end

  # checked, only issue is if @previous_scale is nil, then get_low_high may throw error
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:401
  def get_low_high_previous_current(previous_buckets, current_buckets, previous_scale, current_scale, min_scale); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:368
  def get_scale_change(low, high); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:352
  def grow_buckets(span, buckets); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:421
  def merge_buckets(previous_buckets, current_buckets, current_scale, min_scale, aggregation_temporality); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:359
  def new_mapping(scale); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:386
  def validate_scale(scale); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:393
  def validate_size(size); end
end

# if no reservoir pass from instrument, then use this empty reservoir to avoid no method found error
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:31
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::DEFAULT_RESERVOIR = T.let(T.unsafe(nil), OpenTelemetry::SDK::Metrics::Exemplar::SimpleFixedSizeExemplarReservoir)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:22
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::DEFAULT_SCALE = T.let(T.unsafe(nil), Integer)

# relate to min max scale: https://opentelemetry.io/docs/specs/otel/metrics/sdk/#support-a-minimum-and-maximum-scale
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:21
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:26
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::MAX_MAX_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:23
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::MAX_SCALE = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:25
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::MIN_MAX_SIZE = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_bucket_histogram.rb:24
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialBucketHistogram::MIN_SCALE = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:11
module OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram; end

# Buckets is the fundamental building block of exponential histogram that store bucket/boundary value
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::Buckets
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:16
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:108
  def copy_empty; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:46
  def counts; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:64
  def downscale(amount); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:55
  def get_bucket(key); end

  # grow simply expand the @counts size
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:24
  def grow(needed, max_size); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:104
  def increment_bucket(bucket_index, increment = T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_base; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_base=(_arg0); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_end; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_end=(_arg0); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_start; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:14
  def index_start=(_arg0); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:48
  def length; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:38
  def offset; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/buckets.rb:42
  def offset_counts; end
end

# LogarithmMapping for mapping when scale < 0
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::ExponentMapping
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:16
  def initialize(scale); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:30
  def calculate_min_normal_lower_boundary_index(scale); end

  # for testing
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:37
  def get_lower_boundary(inds); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:22
  def map_to_index(value); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/exponent_mapping.rb:14
  def scale; end
end

# IEEE754 standard for floating-point calculation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:13
module OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754
  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:28
    def get_ieee_754_exponent(value); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:33
    def get_ieee_754_mantissa(value); end
  end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:18
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::EXPONENT_BIAS = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:19
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::EXPONENT_MASK = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:15
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::EXPONENT_WIDTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:17
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MANTISSA_MASK = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:14
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MANTISSA_WIDTH = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:23
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MAX_NORMAL_EXPONENT = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:26
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MAX_NORMAL_VALUE = T.let(T.unsafe(nil), Float)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:22
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MIN_NORMAL_EXPONENT = T.let(T.unsafe(nil), Integer)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:25
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::MIN_NORMAL_VALUE = T.let(T.unsafe(nil), Float)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/ieee_754.rb:20
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::IEEE754::SIGN_MASK = T.let(T.unsafe(nil), Integer)

# Log2eScaleFactor is precomputed scale factor value
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/log2e_scale_factor.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::Log2eScaleFactor
  class << self
    # for testing
    #
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/log2e_scale_factor.rb:22
    def log2e_scale_buckets; end
  end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/log2e_scale_factor.rb:16
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::Log2eScaleFactor::LOG2E_SCALE_BUCKETS = T.let(T.unsafe(nil), Array)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/log2e_scale_factor.rb:14
OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::Log2eScaleFactor::MAX_SCALE = T.let(T.unsafe(nil), Integer)

# LogarithmMapping for mapping when scale > 0
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/logarithm_mapping.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogram::LogarithmMapping
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/logarithm_mapping.rb:16
  def initialize(scale); end

  # for testing
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/logarithm_mapping.rb:35
  def get_lower_boundary(inds); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/logarithm_mapping.rb:23
  def map_to_index(value); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram/logarithm_mapping.rb:14
  def scale; end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::ExponentialHistogramDataPoint < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def attributes; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def attributes=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def count; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def count=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def exemplars; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def exemplars=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def flags; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def flags=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def max; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def max=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def min; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def min=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def negative; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def negative=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def positive; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def positive=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def scale; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def scale=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def start_time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def start_time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def sum; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def sum=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def zero_count; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def zero_count=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def zero_threshold; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
  def zero_threshold=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/exponential_histogram_data_point.rb:13
    def new(*_arg0); end
  end
end

# TODO: Deal with this later
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::HistogramDataPoint < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def attributes; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def attributes=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def bucket_counts; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def bucket_counts=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def count; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def count=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def exemplars; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def exemplars=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def explicit_bounds; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def explicit_bounds=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def max; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def max=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def min; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def min=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def start_time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def start_time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def sum; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def sum=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
  def time_unix_nano=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/histogram_data_point.rb:13
    def new(*_arg0); end
  end
end

# Contains the implementation of the LastValue aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:12
class OpenTelemetry::SDK::Metrics::Aggregation::LastValue
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:19
  def initialize(exemplar_reservoir: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:24
  def collect(start_time, end_time, data_points); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:13
  def exemplar_reservoir; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:36
  def update(increment, attributes, data_points, exemplar_offer: T.unsafe(nil)); end
end

# if no reservoir pass from instrument, then use this empty reservoir to avoid no method found error
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/last_value.rb:16
OpenTelemetry::SDK::Metrics::Aggregation::LastValue::DEFAULT_RESERVOIR = T.let(T.unsafe(nil), OpenTelemetry::SDK::Metrics::Exemplar::SimpleFixedSizeExemplarReservoir)

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
class OpenTelemetry::SDK::Metrics::Aggregation::NumberDataPoint < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def attributes; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def attributes=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def exemplars; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def exemplars=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def start_time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def start_time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def value; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
  def value=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/number_data_point.rb:11
    def new(*_arg0); end
  end
end

# Contains the implementation of the Sum aggregation
# https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#sum-aggregation
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:13
class OpenTelemetry::SDK::Metrics::Aggregation::Sum
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:20
  def initialize(aggregation_temporality: T.unsafe(nil), monotonic: T.unsafe(nil), instrument_kind: T.unsafe(nil), exemplar_reservoir: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:87
  def aggregation_temporality; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:30
  def collect(start_time, end_time, data_points); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:14
  def exemplar_reservoir; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:54
  def monotonic?; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:58
  def update(increment, attributes, data_points, exemplar_offer: T.unsafe(nil)); end
end

# if no reservior pass from instrument, then use this empty reservior to avoid no method found error
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/aggregation/sum.rb:17
OpenTelemetry::SDK::Metrics::Aggregation::Sum::DEFAULT_RESERVOIR = T.let(T.unsafe(nil), OpenTelemetry::SDK::Metrics::Exemplar::SimpleFixedSizeExemplarReservoir)

# The ConfiguratorPatch implements a hook to configure the metrics
# portion of the SDK.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:12
module OpenTelemetry::SDK::Metrics::ConfiguratorPatch
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:19
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:13
  def add_metric_reader(metric_reader); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:57
  def attach_fork_hooks!; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:31
  def configure_metric_readers; end

  # The metrics_configuration_hook method is where we define the setup process for the metrics SDK.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:25
  def metrics_configuration_hook; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/configurator_patch.rb:36
  def wrapped_metric_exporters_from_env; end
end

# The Exemplar module contains the OpenTelemetry metrics reference
# exemplar implementations. Exemplars are example data points for
# aggregated data. They provide specific context to otherwise general
# aggregations. Exemplars allow correlation between aggregated metric
# data and the original API calls where measurements are recorded.
# Exemplars work for trace-metric correlation across any metric, not just
# those that can also be derived from Spans.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar.rb:17
module OpenTelemetry::SDK::Metrics::Exemplar; end

# AlignedHistogramBucketExemplarReservoir
#
# This Exemplar reservoir stores at most one exemplar per histogram bucket.
# It uses reservoir sampling within each bucket to ensure uniform distribution
# of exemplars across the value range.
#
# This is the recommended reservoir for Explicit Bucket Histogram aggregation.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:18
class OpenTelemetry::SDK::Metrics::Exemplar::AlignedHistogramBucketExemplarReservoir < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarReservoir
  # @param boundaries [Array<Numeric>] The bucket boundaries for the histogram
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:23
  def initialize(boundaries: T.unsafe(nil)); end

  # Collects accumulated exemplars and optionally resets state
  #
  # @param attributes [Hash] The attributes to filter from exemplar attributes
  # @param aggregation_temporality [Symbol] :delta or :cumulative
  # @return [Array<Exemplar>] The collected exemplars
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:45
  def collect(attributes: T.unsafe(nil), aggregation_temporality: T.unsafe(nil)); end

  # Offers a measurement to the reservoir for potential sampling
  #
  # @param value [Numeric] The measurement value
  # @param timestamp [Integer] The timestamp in nanoseconds
  # @param attributes [Hash] The complete set of attributes
  # @param context [Context] The OpenTelemetry context
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:34
  def offer(value: T.unsafe(nil), timestamp: T.unsafe(nil), attributes: T.unsafe(nil), context: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:55
  def reset; end

  private

  # Finds the bucket index for a given value
  #
  # @param value [Numeric] The measurement value
  # @return [Integer] The bucket index (0 to boundaries.size)
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:65
  def find_histogram_bucket(value); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/aligned_histogram_bucket_exemplar_reservoir.rb:19
OpenTelemetry::SDK::Metrics::Exemplar::AlignedHistogramBucketExemplarReservoir::DEFAULT_BOUNDARIES = T.let(T.unsafe(nil), Array)

# AlwaysOffExemplarFilter makes no measurements eligible for being an Exemplar.
# Using this ExemplarFilter is as good as disabling Exemplar feature.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/always_off_exemplar_filter.rb:13
class OpenTelemetry::SDK::Metrics::Exemplar::AlwaysOffExemplarFilter < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarFilter
  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/always_off_exemplar_filter.rb:14
    def should_sample?(value, timestamp, attributes, context); end
  end
end

# AlwaysOnExemplarFilter makes all measurements eligible for being an Exemplar.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/always_on_exemplar_filter.rb:12
class OpenTelemetry::SDK::Metrics::Exemplar::AlwaysOnExemplarFilter < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarFilter
  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/always_on_exemplar_filter.rb:13
    def should_sample?(value, timestamp, attributes, context); end
  end
end

# Exemplar is a Struct containing Exemplar data for export.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
class OpenTelemetry::SDK::Metrics::Exemplar::Exemplar < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def filtered_attributes; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def filtered_attributes=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def span_id; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def span_id=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def trace_id; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def trace_id=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def value; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
  def value=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar.rb:13
    def new(*_arg0); end
  end
end

# ExemplarBucket
# Stores a single exemplar measurement and manages its lifecycle
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_bucket.rb:13
class OpenTelemetry::SDK::Metrics::Exemplar::ExemplarBucket
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_bucket.rb:14
  def initialize; end

  # May return an Exemplar and resets the bucket for the next sampling period
  #
  # @param point_attributes [Hash] Attributes already included in the metric data point
  # @return [Exemplar, nil] The collected exemplar or nil if nothing was offered
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_bucket.rb:43
  def collect(point_attributes:); end

  # Offers a measurement to be sampled
  #
  # @param value [Numeric] Measured value
  # @param time_unix_nano [Integer] Measurement observation time in nanoseconds
  # @param attributes [Hash] Measurement attributes
  # @param context [Context] Measurement context
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_bucket.rb:24
  def offer(value:, time_unix_nano:, attributes:, context:); end

  private

  # Reset the bucket state after a collection cycle
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_bucket.rb:63
  def reset; end
end

# ExemplarFilter determines which measurements are eligible for becoming an Exemplar. Available Filters include: AlwaysOn, AlwaysOff, and TraceBased.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_filter.rb:12
class OpenTelemetry::SDK::Metrics::Exemplar::ExemplarFilter
  class << self
    # Returns a {Boolean} value.
    #
    # @param [Integer] value Value of the measurement
    # @param [Hash] attributes Complete set of Attributes of the measurement
    # @param [Context] context Context of the measurement, which covers the Baggage and the current active Span.
    #
    # @return [Boolean]
    #
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_filter.rb:20
    def should_sample?(value, attributes, context); end
  end
end

# ExemplarReservoir base class
# Subclasses must implement offer and collect methods
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_reservoir.rb:13
class OpenTelemetry::SDK::Metrics::Exemplar::ExemplarReservoir
  # Return list of Exemplars based on given attributes
  #
  # @param [Hash] attributes Value of the measurement
  # @param [Symbol] aggregation_temporality Should remove the original exemplars or not, default delta
  #
  # @return [Array] exemplars Array of exemplars
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_reservoir.rb:32
  def collect(attributes: T.unsafe(nil), aggregation_temporality: T.unsafe(nil)); end

  # Returns true if this reservoir never stores exemplars.
  # Used to skip the exemplar filter and timestamp lookups entirely.
  #
  # @return [Boolean]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_reservoir.rb:44
  def noop?; end

  # Store the info into exemplars bucket
  #
  # @param [Numeric] value Value of the measurement
  # @param [Integer] timestamp Time of recording in nanoseconds
  # @param [Hash] attributes Complete set of Attributes of the measurement
  # @param [Context] context SpanContext of the measurement, which covers the Baggage and the current active Span.
  #
  # @return [Nil]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_reservoir.rb:22
  def offer(value: T.unsafe(nil), timestamp: T.unsafe(nil), attributes: T.unsafe(nil), context: T.unsafe(nil)); end

  # Called after dup to reset internal state before reuse for a new attribute set.
  # Subclasses that hold mutable per-attribute state must override this.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/exemplar_reservoir.rb:38
  def reset; end
end

# NoopExemplarReservoir
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/noop_exemplar_reservoir.rb:12
class OpenTelemetry::SDK::Metrics::Exemplar::NoopExemplarReservoir < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarReservoir
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/noop_exemplar_reservoir.rb:15
  def collect(attributes: T.unsafe(nil), aggregation_temporality: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/noop_exemplar_reservoir.rb:19
  def noop?; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/noop_exemplar_reservoir.rb:13
  def offer(value: T.unsafe(nil), timestamp: T.unsafe(nil), attributes: T.unsafe(nil), context: T.unsafe(nil)); end
end

# SimpleFixedSizeExemplarReservoir uses a uniformly-weighted sampling algorithm based on the number of samples the reservoir has seen so far to determine if the offered measurements should be sampled
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:14
class OpenTelemetry::SDK::Metrics::Exemplar::SimpleFixedSizeExemplarReservoir < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarReservoir
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:22
  def initialize(max_size: T.unsafe(nil)); end

  # Reset measurement counter on collection for delta temporality
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:37
  def collect(attributes: T.unsafe(nil), aggregation_temporality: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:52
  def find_histogram_bucket; end

  # Uses a uniformly-weighted sampling algorithm based on the number of samples the reservoir has seen
  # Fill the buckets array first then randomly override existing bucket
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:29
  def offer(value: T.unsafe(nil), timestamp: T.unsafe(nil), attributes: T.unsafe(nil), context: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:47
  def reset; end
end

# Default to number of CPUs for better concurrent performance, fallback to 1
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/simple_fixed_size_exemplar_reservoir.rb:16
OpenTelemetry::SDK::Metrics::Exemplar::SimpleFixedSizeExemplarReservoir::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)

# TraceBasedExemplarFilter is an ExemplarFilter which makes measurements recorded
# in the context of a sampled parent span eligible for being an Exemplar
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/trace_based_exemplar_filter.rb:13
class OpenTelemetry::SDK::Metrics::Exemplar::TraceBasedExemplarFilter < ::OpenTelemetry::SDK::Metrics::Exemplar::ExemplarFilter
  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/exemplar/trace_based_exemplar_filter.rb:14
    def should_sample?(value, timestamp, attributes, context); end
  end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export.rb:10
module OpenTelemetry::SDK::Metrics::Export; end

# Outputs {MetricData} to the console
#
# Potentially useful for exploratory purposes.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:14
class OpenTelemetry::SDK::Metrics::Export::ConsoleMetricPullExporter < ::OpenTelemetry::SDK::Metrics::Export::MetricReader
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:15
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:24
  def export(metrics, timeout: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:32
  def force_flush(timeout: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:20
  def pull; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/console_metric_pull_exporter.rb:36
  def shutdown(timeout: T.unsafe(nil)); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export.rb:11
class OpenTelemetry::SDK::Metrics::Export::ExportError < ::OpenTelemetry::Error; end

# The operation finished with an error.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export.rb:17
OpenTelemetry::SDK::Metrics::Export::FAILURE = T.let(T.unsafe(nil), Integer)

# The InMemoryMetricPullExporter behaves as a Metric Reader and Exporter.
# To be used for testing purposes, not production.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:13
class OpenTelemetry::SDK::Metrics::Export::InMemoryMetricPullExporter < ::OpenTelemetry::SDK::Metrics::Export::MetricReader
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:16
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:26
  def export(metrics, timeout: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:14
  def metric_snapshots; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:22
  def pull; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:33
  def reset; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/in_memory_metric_pull_exporter.rb:39
  def shutdown; end
end

# MetricReader provides a minimal example implementation.
# It is not required to subclass this class to provide an implementation
# of MetricReader, provided the interface is satisfied.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:14
class OpenTelemetry::SDK::Metrics::Export::MetricReader
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:17
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:21
  def collect; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:29
  def force_flush(timeout: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:15
  def metric_store; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/metric_reader.rb:25
  def shutdown(timeout: T.unsafe(nil)); end
end

# PeriodicMetricReader provides a minimal example implementation.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:12
class OpenTelemetry::SDK::Metrics::Export::PeriodicMetricReader < ::OpenTelemetry::SDK::Metrics::Export::MetricReader
  # Returns a new instance of the {PeriodicMetricReader}.
  #
  # @param [Integer] export_interval_millis the maximum interval time.
  #   Defaults to the value of the OTEL_METRIC_EXPORT_INTERVAL environment
  #   variable, if set, or 60_000.
  # @param [Integer] export_timeout_millis the maximum export timeout.
  #   Defaults to the value of the OTEL_METRIC_EXPORT_TIMEOUT environment
  #   variable, if set, or 30_000.
  # @param [MetricReader] exporter the (duck type) MetricReader to where the
  #   recorded metrics are pushed after certain interval.
  #
  # @return a new instance of the {PeriodicMetricReader}.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:25
  def initialize(export_interval_millis: T.unsafe(nil), export_timeout_millis: T.unsafe(nil), exporter: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:81
  def after_fork; end

  # Check both @thread and @continue object to determine if current
  # PeriodicMetricReader is still alive. If one of them is true/alive,
  # then PeriodicMetricReader is determined as alive
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:91
  def alive?; end

  # Export all metrics to the configured `Exporter` that have not yet
  # been exported.
  #
  # This method should only be called in cases where it is absolutely
  # necessary, such as when using some FaaS providers that may suspend
  # the process after an invocation, but before the `PeriodicMetricReader` exports
  # the completed metrics.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] SUCCESS if no error occurred, FAILURE if a
  #   non-specific failure occurred.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:74
  def force_flush(timeout: T.unsafe(nil)); end

  # Shuts the @thread down and set @continue to false; it will block
  # until the shutdown thread is finished.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] SUCCESS if no error occurred, FAILURE if a
  #   non-specific failure occurred.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:48
  def shutdown(timeout: T.unsafe(nil)); end

  private

  # Helper function for the defined exporter to export metrics.
  # It only exports if the collected metrics are not an empty array (collect returns an Array).
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] SUCCESS if no error occurred, FAILURE if a
  #   non-specific failure occurred
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:123
  def export(timeout: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:136
  def lock(&block); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:132
  def report_result(result_code); end

  # Start a thread that continously export metrics within fixed duration.
  # The wait mechanism is using to check @mutex lock with conditional variable
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export/periodic_metric_reader.rb:99
  def start; end
end

# The operation finished successfully.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export.rb:14
OpenTelemetry::SDK::Metrics::Export::SUCCESS = T.let(T.unsafe(nil), Integer)

# The operation timed out.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/export.rb:20
OpenTelemetry::SDK::Metrics::Export::TIMEOUT = T.let(T.unsafe(nil), Integer)

# ForkHooks implements methods to run callbacks before and after forking a Process by overriding Process::_fork
# This is used to ensure that the PeriodicMetricReader is restarted after forking
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/fork_hooks.rb:12
module OpenTelemetry::SDK::Metrics::ForkHooks
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/fork_hooks.rb:26
  def _fork; end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/fork_hooks.rb:20
    def after_fork; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/fork_hooks.rb:13
    def attach!; end
  end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/synchronous_instrument.rb:10
module OpenTelemetry::SDK::Metrics::Instrument; end

# {AsynchronousInstrument} contains the common functionality shared across
# the asynchronous instruments SDK instruments.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:13
class OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:16
  def initialize(name, unit, description, callback, instrumentation_scope, meter_provider, exemplar_filter, exemplar_reservoir); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:84
  def add_attributes(attributes); end

  # The API MUST support creation of asynchronous instruments by passing zero or more callback functions
  # to be permanently registered to the newly created instrument.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:55
  def init_callback(callback); end

  # Where the API supports registration of callback functions after asynchronous instrumentation creation,
  # the user MUST be able to undo registration of the specific callback after its registration by some means.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:67
  def register_callback(callback); end

  # @api private
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:34
  def register_with_new_metric_store(metric_store, aggregation: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:80
  def timeout(timeout); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:76
  def unregister(callback); end

  private

  # Adding the exemplar to reservoir
  # Only record the exemplar if exemplar_filter decide to sample/record it
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:98
  def exemplar_offer(value, attributes); end

  # update the observed value (after calling observe)
  # invoke callback will execute callback and export metric_data that is observed
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:92
  def update(timeout, attributes); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/asynchronous_instrument.rb:14
OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument::NOOP_EXEMPLAR_RESERVOIR = T.let(T.unsafe(nil), OpenTelemetry::SDK::Metrics::Exemplar::NoopExemplarReservoir)

# {Counter} is the SDK implementation of {OpenTelemetry::Metrics::Counter}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/counter.rb:12
class OpenTelemetry::SDK::Metrics::Instrument::Counter < ::OpenTelemetry::SDK::Metrics::Instrument::SynchronousInstrument
  # Increment the Counter by a fixed amount.
  #
  # @param [numeric] increment The increment amount, which MUST be a non-negative numeric value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/counter.rb:27
  def add(increment, attributes: T.unsafe(nil)); end

  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/counter.rb:16
  def instrument_kind; end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/counter.rb:44
  def default_aggregation; end
end

# {Gauge} is the SDK implementation of {OpenTelemetry::Metrics::Gauge}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/gauge.rb:12
class OpenTelemetry::SDK::Metrics::Instrument::Gauge < ::OpenTelemetry::SDK::Metrics::Instrument::SynchronousInstrument
  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/gauge.rb:16
  def instrument_kind; end

  # Record the absolute value of the Gauge.
  #
  # @param [numeric] value The current absolute value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/gauge.rb:27
  def record(value, attributes: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/gauge.rb:40
  def default_aggregation; end
end

# {Histogram} is the SDK implementation of {OpenTelemetry::Metrics::Histogram}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/histogram.rb:12
class OpenTelemetry::SDK::Metrics::Instrument::Histogram < ::OpenTelemetry::SDK::Metrics::Instrument::SynchronousInstrument
  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/histogram.rb:16
  def instrument_kind; end

  # Updates the statistics with the specified amount.
  #
  # @param [numeric] amount The amount of the Measurement, which MUST be a non-negative numeric value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/histogram.rb:27
  def record(amount, attributes: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/histogram.rb:37
  def default_aggregation; end
end

# {ObservableCounter} is the SDK implementation of {OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument}.
# Asynchronous Counter is an asynchronous Instrument which reports monotonically increasing value(s) when the instrument is being observed.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_counter.rb:13
class OpenTelemetry::SDK::Metrics::Instrument::ObservableCounter < ::OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument
  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_counter.rb:17
  def instrument_kind; end

  # Observe the ObservableCounter with fixed timeout duration.
  #
  # @param [int] timeout The timeout duration for callback to run, which MUST be a non-negative numeric value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_counter.rb:28
  def observe(timeout: T.unsafe(nil), attributes: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_counter.rb:34
  def default_aggregation; end
end

# {ObservableGauge} is the SDK implementation of {OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument}.
# Asynchronous Gauge is an asynchronous Instrument which reports non-additive value(s) (e.g. the room temperature)
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_gauge.rb:13
class OpenTelemetry::SDK::Metrics::Instrument::ObservableGauge < ::OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument
  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_gauge.rb:17
  def instrument_kind; end

  # Observe the Gauge with fixed timeout duration.
  #
  # @param [int] timeout The timeout duration for callback to run, which MUST be a non-negative numeric value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_gauge.rb:28
  def observe(timeout: T.unsafe(nil), attributes: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_gauge.rb:34
  def default_aggregation; end
end

# {ObservableUpDownCounter} is the SDK implementation of {OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument}.
# Asynchronous UpDownCounter is an asynchronous Instrument which reports additive value(s) (e.g. the process heap size)
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_up_down_counter.rb:13
class OpenTelemetry::SDK::Metrics::Instrument::ObservableUpDownCounter < ::OpenTelemetry::SDK::Metrics::Instrument::AsynchronousInstrument
  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_up_down_counter.rb:17
  def instrument_kind; end

  # Observe the UpDownCounter with fixed timeout duration.
  #
  # @param [int] timeout The timeout duration for callback to run, which MUST be a non-negative numeric value.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_up_down_counter.rb:28
  def observe(timeout: T.unsafe(nil), attributes: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/observable_up_down_counter.rb:34
  def default_aggregation; end
end

# {SynchronousInstrument} contains the common functionality shared across
# the synchronous instruments SDK instruments.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/synchronous_instrument.rb:13
class OpenTelemetry::SDK::Metrics::Instrument::SynchronousInstrument
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/synchronous_instrument.rb:14
  def initialize(name, unit, description, instrumentation_scope, meter_provider, exemplar_filter, exemplar_reservoir); end

  # @api private
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/synchronous_instrument.rb:28
  def register_with_new_metric_store(metric_store, aggregation: T.unsafe(nil)); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/synchronous_instrument.rb:46
  def update(value, attributes); end
end

# {UpDownCounter} is the SDK implementation of {OpenTelemetry::Metrics::UpDownCounter}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/up_down_counter.rb:12
class OpenTelemetry::SDK::Metrics::Instrument::UpDownCounter < ::OpenTelemetry::SDK::Metrics::Instrument::SynchronousInstrument
  # Increment or decrement the UpDownCounter by a fixed amount.
  #
  # @param [Numeric] amount The amount to be added, can be positive, negative or zero.
  # @param [Hash{String => String, Numeric, Boolean, Array<String, Numeric, Boolean>}] attributes
  #   Values must be non-nil and (array of) string, boolean or numeric type.
  #   Array values must not contain nil elements and all elements must be of
  #   the same basic type (string, numeric, boolean).
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/up_down_counter.rb:27
  def add(amount, attributes: T.unsafe(nil)); end

  # Returns the instrument kind as a Symbol
  #
  # @return [Symbol]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/up_down_counter.rb:16
  def instrument_kind; end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/instrument/up_down_counter.rb:37
  def default_aggregation; end
end

# {Meter} is the SDK implementation of {OpenTelemetry::Metrics::Meter}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:13
class OpenTelemetry::SDK::Metrics::Meter < ::OpenTelemetry::Metrics::Meter
  # @api private
  #
  # Returns a new {Meter} instance.
  #
  # @param [String] name Instrumentation package name
  # @param [String] version Instrumentation package version
  #
  # @return [Meter]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:24
  def initialize(name, version, meter_provider); end

  # @api private
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:56
  def add_metric_reader(metric_reader); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:62
  def create_instrument(kind, name, unit, description, callback, exemplar_filter, exemplar_reservoir); end

  # Multiple-instrument callbacks
  # Callbacks registered after the time of instrument creation MAY be associated with multiple instruments.
  # Related spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#multiple-instrument-callbacks
  # Related spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#synchronous-instrument-api
  #
  # @param [Array] instruments A list (or tuple, etc.) of Instruments used in the callback function.
  # @param [Proc] callback A callback function
  #
  # It is RECOMMENDED that the API authors use one of the following forms for the callback function:
  # The list (or tuple, etc.) returned by the callback function contains (Instrument, Measurement) pairs.
  # the Observable Result parameter receives an additional (Instrument, Measurement) pairs
  # Here it chose the second form
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:43
  def register_callback(instruments, callback); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:49
  def unregister(instruments, callback); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:82
  def utf8mb3_encoding?(string); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter.rb:14
OpenTelemetry::SDK::Metrics::Meter::NAME_REGEX = T.let(T.unsafe(nil), Regexp)

# {MeterProvider} is the SDK implementation of {OpenTelemetry::Metrics::MeterProvider}.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:14
class OpenTelemetry::SDK::Metrics::MeterProvider < ::OpenTelemetry::Metrics::MeterProvider
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:20
  def initialize(resource: T.unsafe(nil)); end

  # Adds a new MetricReader to this {MeterProvider}.
  #
  # @param metric_reader the new MetricReader to be added.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:110
  def add_metric_reader(metric_reader); end

  # A View provides SDK users with the flexibility to customize the metrics that are output by the SDK.
  #
  # Example:
  #
  #   OpenTelemetry.meter_provider.add_view('test', :aggregation => Aggregation::Drop.new,
  #                                         :type => :counter, :unit => 'smidgen',
  #                                         :meter_name => 'test', :meter_version => '1.0')
  #
  #
  # @param [String] name Name of the view.
  # @param [optional Hash] options For more precise matching, {View} and {MetricsStream}
  #   options may include:
  #     aggregation: An instance of an aggregation class, e.g. {ExplicitBucketHistogram}, {Sum}, {LastValue}
  #     type: A Symbol representing the instrument kind, e.g. :observable_gauge, :counter
  #     unit: A String matching an instrumentation unit, e.g. 'smidgen'
  #     meter_name: A String matching a meter name, e.g. meter_provider.meter('sample_meter_name', version: '1.2.0'), would be 'sample_meter_name'
  #     meter_version: A String matching a meter version, e.g. meter_provider.meter('sample_meter_name', version: '1.2.0'), would be '1.2.0'
  #
  # @return [nil] returns nil
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:180
  def add_view(name, **options); end

  # turn off exemplar_filter by setting the exemplar_fitler to AlwaysOffExemplarFilter
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:156
  def disable_exemplar_filter; end

  # Adds a new exemplar_filter to replace exist exemplar_filter
  # Default to TraceBasedExemplarFilter
  #
  # @param exemplar_filter the new ExemplarFilter to be added.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:151
  def enable_exemplar_filter(exemplar_filter: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:18
  def exemplar_filter; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:133
  def exemplar_filter_setup; end

  # This method provides a way for provider to notify the registered
  # {MetricReader} instances, so they can do as much as they could to consume
  # or send the metrics. Note: unlike Push Metric Exporter which can send data on
  # its own schedule, Pull Metric Exporter can only send the data when it is
  # being asked by the scraper, so ForceFlush would not make much sense.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] Export::SUCCESS if no error occurred, Export::FAILURE if
  #   a non-specific failure occurred, Export::TIMEOUT if a timeout occurred.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:87
  def force_flush(timeout: T.unsafe(nil)); end

  # Returns a {Meter} instance.
  #
  # @param [String] name Instrumentation package name
  # @param [optional String] version Instrumentation package version
  #
  # @return [Meter]
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:36
  def meter(name, version: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:18
  def metric_readers; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:131
  def register_asynchronous_instrument(instrument); end

  # @api private
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:124
  def register_synchronous_instrument(instrument); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:18
  def registered_views; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:18
  def resource; end

  # Attempts to stop all the activity for this {MeterProvider}.
  #
  # Calls MetricReader#shutdown for all registered MetricReaders.
  #
  # After this is called all the newly created {Meter}s will be no-op.
  #
  # @param [optional Numeric] timeout An optional timeout in seconds.
  # @return [Integer] Export::SUCCESS if no error occurred, Export::FAILURE if
  #   a non-specific failure occurred, Export::TIMEOUT if a timeout occurred.
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:56
  def shutdown(timeout: T.unsafe(nil)); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
class OpenTelemetry::SDK::Metrics::MeterProvider::Key < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
  def name; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
  def name=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
  def version; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
  def version=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/meter_provider.rb:15
    def new(*_arg0); end
  end
end

# @api private
#
# The State module provides SDK internal functionality that is not a part of the
# public API.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state.rb:14
module OpenTelemetry::SDK::Metrics::State; end

# @api private
#
# The AsynchronousMetricStream class provides SDK internal functionality that is not a part of the
# public API. It extends MetricStream to support asynchronous instruments.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:15
class OpenTelemetry::SDK::Metrics::State::AsynchronousMetricStream < ::OpenTelemetry::SDK::Metrics::State::MetricStream
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:18
  def initialize(name, description, unit, instrument_kind, meter_provider, instrumentation_scope, aggregation, callback, timeout, attributes, exemplar_filter, exemplar_reservoir); end

  # When collect, if there are asynchronous SDK Instruments involved, their callback functions will be triggered.
  # Related spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#collect
  # invoke_callback will update the data_points in aggregation
  #
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:45
  def collect(start_time, end_time); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:52
  def invoke_callback(timeout, attributes); end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:84
  def safe_guard_callback(callback, timeout: T.unsafe(nil)); end
end

# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/asynchronous_metric_stream.rb:16
OpenTelemetry::SDK::Metrics::State::AsynchronousMetricStream::DEFAULT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# MetricData is a Struct containing {MetricStream} data for export.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
class OpenTelemetry::SDK::Metrics::State::MetricData < ::Struct
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def aggregation_temporality; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def aggregation_temporality=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def data_points; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def data_points=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def description; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def description=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def instrument_kind; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def instrument_kind=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def instrumentation_scope; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def instrumentation_scope=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def is_monotonic; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def is_monotonic=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def name; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def name=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def resource; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def resource=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def start_time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def start_time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def time_unix_nano; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def time_unix_nano=(_); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def unit; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
  def unit=(_); end

  class << self
    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
    def [](*_arg0); end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
    def inspect; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
    def keyword_init?; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
    def members; end

    # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_data.rb:12
    def new(*_arg0); end
  end
end

# @api private
#
# The MetricStore module provides SDK internal functionality that is not a part of the
# public API.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_store.rb:15
class OpenTelemetry::SDK::Metrics::State::MetricStore
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_store.rb:16
  def initialize; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_store.rb:33
  def add_metric_stream(metric_stream); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_store.rb:23
  def collect; end
end

# @api private
#
# The MetricStream class provides SDK internal functionality that is not a part of the
# public API.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:16
class OpenTelemetry::SDK::Metrics::State::MetricStream
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:19
  def initialize(name, description, unit, instrument_kind, meter_provider, instrumentation_scope, aggregation, exemplar_filter, exemplar_reservoir); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:85
  def aggregate_metric_data(start_time, end_time, aggregation: T.unsafe(nil), data_points: T.unsafe(nil)); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:46
  def collect(start_time, end_time); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def data_points; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def description; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:112
  def empty_data_point?; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:106
  def find_registered_view; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def instrument_kind; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def instrumentation_scope; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def name; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:122
  def should_offer_exemplar?(value, attributes); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:130
  def to_s; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:17
  def unit; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/state/metric_stream.rb:65
  def update(value, attributes); end
end

# Current OpenTelemetry metrics sdk version
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/version.rb:11
OpenTelemetry::SDK::Metrics::VERSION = T.let(T.unsafe(nil), String)

# A View provides SDK users with the flexibility to customize the metrics that are output by the SDK.
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view.rb:11
module OpenTelemetry::SDK::Metrics::View; end

# RegisteredView is an internal class used to match Views with a given {MetricStream}
#
# pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:12
class OpenTelemetry::SDK::Metrics::View::RegisteredView
  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:15
  def initialize(name, **options); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:13
  def aggregation; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:13
  def attribute_keys; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:24
  def match_instrument?(metric_stream); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:13
  def name; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:34
  def name_match(stream_name); end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:13
  def regex; end

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:38
  def valid_aggregation?; end

  private

  # pkg:gem/opentelemetry-metrics-sdk#lib/opentelemetry/sdk/metrics/view/registered_view.rb:44
  def generate_regex_pattern(view_name); end
end
